name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.9" }
      - run: |
          python -V
          python -m pip install -U pip
          python -m pip install -r PRIVATE-BACK/requirements.txt
      - run: python -m pytest -q PRIVATE-BACK/Backend || [ $? -eq 5 ]

  deploy:
    needs: ci
    runs-on: self-hosted        # ← 서버의 러너
    steps:
      - uses: actions/checkout@v4
      - name: Install & restart on server
        run: |
          /usr/bin/python3.9 -V
          /usr/bin/python3.9 -m pip install -U pip
          /usr/bin/python3.9 -m pip install -r /root/PRIVATE-BACK/requirements.txt
          systemctl restart myapp.service
